APK=/home/votarytech/Desktop/qt-qml/333333/build/Qt_5_15_2_for_Android_Multi_Abi-Debug/android-build/build/outputs/apk/debug/android-build-debug.apk
echo Deploying to OKT507...
adb connect 192.168.1.100:5555
adb install -r 17505APK
echo Setting as default launcher...
adb shell cmd package set-home-activity org.votary.infotainment/org.qtproject.qt5.android.bindings.QtActivity
APK=/home/votarytech/Desktop/qt-qml/333333/build/Qt_5_15_2_for_Android_Multi_Abi-Debug/android-build/build/outputs/apk/debug/android-build-debug.apk
echo Deploying to OKT507...
adb connect 192.168.1.100:5555
adb install -r 17521APK
echo Setting as default launcher...
adb shell cmd package set-home-activity org.votary.infotainment/org.qtproject.qt5.android.bindings.QtActivity
